<a href="https://colab.research.google.com/github/iammiori/DataAnalysisAndPractice/blob/master/PCC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import pandas as pd
import numpy as np

In [0]:
rating_load = np.load("/content/gdrive/My Drive/rating_numpy.npy")

In [0]:
rating_load[np.isnan(rating_load)] = float(0.0)
rating_load

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [0]:
def PCC(a):
    NumUsers = np.size(a,axis=0)
    Sim = np.full((NumUsers,NumUsers), 0.0)
    
    mean = np.nanmean(np.where(a!=0,a,np.nan),axis=1)
    
    for u in range(0,NumUsers):
        for v in range(u,NumUsers):
            arridx_u = np.where(a[u,]==0)
            arridx_v = np.where(a[v,]==0)
            arridx = np.concatenate((arridx_u,arridx_v),axis=None)
            
            U = np.delete(a[u,],arridx)
            V = np.delete(a[v,],arridx)
            U = U-mean[u]
            V = V-mean[v]
            
            InnerDot = np.dot(U,V)
            NormU = np.linalg.norm(U)
            NormV = np.linalg.norm(V)
            Sim[u,v] = InnerDot/(NormU*NormV)
            Sim[v,u] = Sim[u,v]
    return Sim

In [0]:
pcc_sim = PCC(rating_load)

In [0]:
np.save("/content/gdrive/My Drive/pcc_sim",pcc_sim)

In [0]:
pcc_load = np.load("/content/gdrive/My Drive/pcc_sim.npy")

In [19]:
pcc_load

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [0]:
pccsim_nonzero = np.transpose(np.nonzero(pcc_load))

In [21]:
pccsim_nonzero

array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [9999, 9997],
       [9999, 9998],
       [9999, 9999]])

In [32]:
pcc_df = pd.DataFrame(rating_load).T
pcc_df = pcc_df.fillna(0.0)
pcc_df.head()

0     1     2     3     4     5     ...  9994  9995  9996  9997  9998  9999
0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
1   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
2   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
3   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
4   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0

[5 rows x 10000 columns]

In [34]:
pcc_corr = pcc_df.corr(method = 'pearson')
print(pcc_corr)

         0        1        2        3     ...     9996     9997     9998     9999
0     1.00000 -0.00012 -0.00012 -0.00012  ... -0.00012 -0.00012 -0.00012 -0.00012
1    -0.00012  1.00000 -0.00012 -0.00012  ... -0.00012 -0.00012 -0.00012 -0.00012
2    -0.00012 -0.00012  1.00000 -0.00012  ... -0.00012 -0.00012 -0.00012 -0.00012
3    -0.00012 -0.00012 -0.00012  1.00000  ... -0.00012 -0.00012 -0.00012 -0.00012
4    -0.00012 -0.00012 -0.00012 -0.00012  ... -0.00012 -0.00012 -0.00012 -0.00012
5    -0.00012 -0.00012 -0.00012 -0.00012  ... -0.00012 -0.00012 -0.00012 -0.00012
6    -0.00012 -0.00012 -0.00012 -0.00012  ... -0.00012 -0.00012 -0.00012 -0.00012
7    -0.00012 -0.00012 -0.00012 -0.00012  ... -0.00012 -0.00012 -0.00012 -0.00012
8    -0.00012 -0.00012 -0.00012 -0.00012  ... -0.00012 -0.00012 -0.00012 -0.00012
9    -0.00012 -0.00012 -0.00012 -0.00012  ... -0.00012 -0.00012 -0.00012 -0.00012
10   -0.00012 -0.00012 -0.00012 -0.00012  ... -0.00012 -0.00012 -0.00012 -0.00012
11   -0.00012 -0