In [14]:
import json,csv
headers = True
def convert(filein,fileout):
    global headers 
    with open(filein,encoding='UTF-8') as jsonf, open(fileout,"w",encoding="UTF-8") as csvf:
        for line in jsonf:
            data = json.loads(line)
            
            data.pop("yelping_since")
            
            if headers:
                keys = []
                for k,v in data.items():
                    keys.append(k)
                writer = csv.DictWriter(csvf,fieldnames=keys)
                writer.writeheader()
                headers= False
            if data['review_count'] >=1457:
                writer.writerow(data)

In [15]:
convert("../dataset/user.json","../dataset/user.csv")

In [16]:
import pandas as pd

In [18]:
df = pd.read_csv("../dataset/user.csv")
df.head()

user_id     name  review_count  useful  funny   cool  \
0  zzpgpo54-_P-4rzzBtOuLQ  Aurélie          1563    4172   1661   3246   
1  eSlOI3GhroEtcbaD_nFXJQ    Jason          2518   16349   8340  13924   
2  U4INQZOPSUaj8hMjLlZ3KA  Michael          4308   22757  10209  16249   
3  XkLK2iBsgqF6mWwDfRgqqQ    Seong          1525    4012   2862   3573   
4  lConjPFTZqz4zWELK_EJtw    Keila          2097   17430   9232  13626   

                                               elite  \
0                           2013,2014,2016,2017,2018   
1                 2012,2013,2014,2015,2016,2017,2018   
2                 2008,2010,2011,2012,2013,2014,2015   
3  2007,2008,2009,2010,2011,2012,2013,2014,2015,2016   
4                      2010,2011,2012,2013,2014,2015   

                                             friends  fans  average_stars  \
0  8pzdMS8Mbppx9Xuf4ekCTA, Fcw-Rza7kEtavc_88t-BSg...    99           3.89   
1  emkgr9xghy66fU58fwnRgQ, _ahqZJFXDNpeiKROkIjGJg...   251           3.61   
2  yqumc_CYlWeghZ5vM3Ilyw, mX84lBw8jwS2uQqdgKu_aA...   912           3.88   
3  2zoKsAEeFuBhEm8g5jhPsg, Y3QU8Jj3lYuVa2LmunvnRg...   124           3.75   
4  Aes5gG5F6JXPmIH9N4TX9w, AyxN-JsfGXJ-3RRz7BZYXg...   447           3.89   

   ...  compliment_more  compliment_profile  compliment_cute  compliment_list  \
0  ...                9                  16               29                8   
1  ...               84                  59               18               16   
2  ...               75                  43               13               52   
3  ...               75                  56              207               23   
4  ...              222                 149               49               59   

   compliment_note  compliment_plain  compliment_cool  compliment_funny  \
0              354               776              559               559   
1              361              2861             2267              2267   
2              442               656              801               801   
3              557               497             1125              1125   
4              491              1634             1892              1892   

   compliment_writer  compliment_photos  
0                 75                119  
1                274                218  
2                663                634  
3                139                 43  
4                873               1234  

[5 rows x 21 columns]

In [1]:
import os

In [3]:
os.path.exists("user.json")

False

In [1]:
import pandas as pd

In [10]:
user_df= pd.read_csv("../dataset/user.csv")

In [12]:
user_df

user_id     name  review_count
0    zzpgpo54-_P-4rzzBtOuLQ  Aurélie          1563
1    eSlOI3GhroEtcbaD_nFXJQ    Jason          2518
2    U4INQZOPSUaj8hMjLlZ3KA  Michael          4308
3    XkLK2iBsgqF6mWwDfRgqqQ    Seong          1525
4    lConjPFTZqz4zWELK_EJtw    Keila          2097
..                      ...      ...           ...
495  XjrLnxoD8_OC9nnKg5H2_Q    Hideo          2006
496  6VytXlGLnQnXXCrhvT0AJw    Libby          1469
497  GCuDiPUKYxhgFHP5LqJa2Q   Gloria          1490
498  vYMvOTL31e0KbTo9Hd0tjg     Nick          1591
499  5hfKGSTC6gkamIfl6BZm6A    Matze          2815

[500 rows x 3 columns]

In [13]:
user_df.sort_values(by="review_count",ascending=False)

user_id     name  review_count
477  8k3aO-mPeyhbR5HUucA5aA   Victor         13278
77   RtGqdDBvvBCjcu5dUqwfzA    Shila         12390
16   hWDybu_KvYLSdEFzGrniTw    Bruce         10022
481  P5bUL3Engv-2z6kKohB6qQ      Kim          9821
158  8RcEwGrFIgkt9WQ35E6SnQ   George          7750
..                      ...      ...           ...
434  YS4pJyJjRURaiBgrlDeohg     Nick          1461
398  pnfVIB7UhvCQ7X2K0Q2XIw  Retired          1461
462  pRfWy61wU9e1nrCVrOEWLA  Richard          1458
120  I2qJvA0tbGdZJ3XrwzwfzA  Randoll          1457
216  6tDMGnbO4m8ENlUvG7r0eA     Sean          1457

[500 rows x 3 columns]

In [14]:
user_id_list = []
for i in range(len(user_df)):
    tmp = user_df["user_id"].iloc[i]
    user_id_list.append(tmp)
len(user_id_list)

500

In [15]:
user_name_list = []
for i in range(len(user_df)):
    tmp = user_df["name"].iloc[i]
    user_name_list.append(tmp)
len(user_name_list)

500

In [9]:
import numpy as np
import math

In [72]:
ui_matrix=np.load("../dataset/real_matrix.npy")
ui_matrix.shape

(380, 21601)

In [116]:
test = pd.read_csv("../dataset/review_top.csv")
test.head()

user                    store  stars
0      Chad  China King Super Buffet    3.0
1      Chad            Panda Express    3.0
2   Margret                      Gap    3.0
3   Shannon        Encore Beach Club    2.0
4  Jennifer               Wright Bar    4.0

In [95]:
len(ui_matrix)

380

In [129]:
def NDCG(ui_matrix, est_matrix, k):
    null=[]
    #If number of not-null in each user is greater than k, the calculation will be failed
    #thus those row should be removed from calculation
    for i in range(len(ui_matrix)):
        a=np.count_nonzero(~np.isnan(ui_matrix[i]))
        if a<k:
            null.append(i)
    #ui_matrix=np.delete(ui_matrix, [null], 0)
    est_matrix=np.delete(est_matrix, [null], 0)
    
    
    #NDCG calculation
    dcg_sum=0
    idcg_sum=0
    for i in range(len(ui_matrix)):
        #Exclues all the null value from crresponding user(row) of both matrix
        rui=ui_matrix[i]
        rui_bar=est_matrix[i]
        rui=rui[~np.isnan(rui)]
        rui_bar=rui_bar[~np.isnan(rui_bar)]
        
        #Ranking list of estimated rating(rui_bar)
        temp = rui_bar.argsort()[::-1]
        est_rank = np.empty_like(temp)
        est_rank[temp] = np.arange(len(est_rank))
        est_rank=list(est_rank)
        
        #DCG value of each user (Summed up in one value, dcg_sum)
        dcg_sum+=rui[est_rank.index(0)]
        for j in range(1, k):
            dcg_sum+=(rui[est_rank.index(j)]/math.log2(j+1))
        
        #Ranking list of original rating(rui)
        temp = rui.argsort()[::-1]
        ori_rank = np.empty_like(temp)
        ori_rank[temp] = np.arange(len(ori_rank))
        ori_rank=list(ori_rank)
        
        #IDCG value of each user (Summed up in one value, idcg_sum)
        idcg_sum+=rui[ori_rank.index(0)]
        for j in range(1, k):
            idcg_sum+=(rui[ori_rank.index(j)]/math.log2(j+1))

    dcg=dcg_sum/np.abs(len(ui_matrix))
    idcg=idcg_sum/np.abs(len(ui_matrix))
    print("DCG : %f"%(dcg))
    print("IDCG : %f"%(idcg))
    print("NDCG : %f"%(dcg/idcg))

In [130]:
NDCG(ui_matrix, ui_matrix, 10)

KeyError: 0

In [107]:
import pandas as pd
import numpy as np

In [108]:
rating_file = pd.read_csv("../dataset/knnbasic_result.csv")

In [109]:
rating_file.head()

Unnamed: 0      user                     item  r_ui       est       err
0           0      Chad  China King Super Buffet   3.0  3.112563  0.112563
1           1      Chad            Panda Express   3.0  2.717246  0.282754
2           2   Margret                      Gap   3.0  3.462684  0.462684
3           3   Shannon        Encore Beach Club   2.0  2.832106  0.832106
4           4  Jennifer               Wright Bar   4.0  3.463067  0.536933

In [110]:
predict_csv = rating_file[["user","item","est"]]

In [111]:
predict_csv.head()

user                     item       est
0      Chad  China King Super Buffet  3.112563
1      Chad            Panda Express  2.717246
2   Margret                      Gap  3.462684
3   Shannon        Encore Beach Club  2.832106
4  Jennifer               Wright Bar  3.463067

In [112]:
predict_matrix = predict_csv.reset_index().pivot_table(index="user",columns="item",values="est")

In [113]:
predict_matrix.shape

(380, 21601)

In [114]:
est_matrix = predict_matrix

In [115]:
est_matrix.shape

(380, 21601)

In [117]:
real_matrix = test.reset_index().pivot_table(index="user",columns="store",values="stars")
real_matrix.shape

(380, 21601)

In [118]:
ui_matrix=real_matrix

In [119]:
ui_matrix.shape

(380, 21601)

In [120]:
test.isnull().sum()

user     0
store    0
stars    0
dtype: int64

In [121]:
predict_csv.isnull().sum()

user    0
item    0
est     0
dtype: int64

In [99]:
def dcg_at_k(r, k):
    r = np.asfarray(r)[:k]
    if r.size:
        return r[0] + np.sum(r[1:] / np.log2(np.arange(2, r.size + 1)))
    return 0.

def ndcg_at_k(r, k):
    dcg_max = dcg_at_k(sorted(r, reverse=True), k)
    if not dcg_max:
        return 0.
    return dcg_at_k(r, k) / dcg_max

In [100]:
array = np.array([4,2,7,1])
array

array([4, 2, 7, 1])

In [101]:
temp = array.argsort()
temp

array([3, 1, 0, 2], dtype=int64)

In [102]:
array[temp] # 랭크순으로 정렬

array([1, 2, 4, 7])

In [103]:
real = np.array([2, 1, 4, 5])

est = np.array([3.23, 2.13, 3.12, 4.58])

real[np.argsort(-est)] # -est (음수처리를 통해 역순정렬)

array([5, 2, 4, 1])

In [104]:
dcg_at_k(real[np.argsort(-est)], 4)

10.023719014285831

In [105]:
ndcg_at_k(real[np.argsort(-est)], 4)

0.9314114356940674

In [106]:
def nDCG(y_true,y_pred,k=5):
    y_true[y_true==-1] = 0
#    pred = copy.deepcopy(y_pred)
    ndcg = np.zeros(k)
    rank_mat = np.argsort(-y_pred)
    sumY = np.sum(y_true,1).ravel()
    Ypred = np.zeros([y_true.shape[0],k])
    normFac = np.zeros([y_true.shape[0],k])
    
    for i in range(k):
#        Jidx = np.array(pred.argmax(1)).ravel()
        Jidx = rank_mat[:,i]
        Iidx = np.array(range(len(Jidx)))
        lbls = y_true[Iidx,Jidx]
#        pred[Iidx,Jidx] = 0
        Ypred[:,i] = lbls/np.log2(2+i)
        sY = np.sum(Ypred[:,:i+1],1)
        
        
        normFac[:,i] = ( (np.float32(sumY>=i+1)+1e-12)/np.log2(2+i) )
        sF = np.sum(normFac[:,:i+1],1)
        ndcg[i] = np.sum(sY/sF)/y_pred.shape[0]
#        print np.sum(sY),sF.sum()
    return ndcg 

In [122]:
nDCG(ui_matrix,est_matrix,k=10)

TypeError: '(slice(None, None, None), 0)' is an invalid key

In [123]:
def dcg_at_k(r, k, method=0):
    """Score is discounted cumulative gain (dcg)
    Relevance is positive real values.  Can use binary
    as the previous methods.
    Example from
    http://www.stanford.edu/class/cs276/handouts/EvaluationNew-handout-6-per.pdf
    >>> r = [3, 2, 3, 0, 0, 1, 2, 2, 3, 0]
    >>> dcg_at_k(r, 1)
    3.0
    >>> dcg_at_k(r, 1, method=1)
    3.0
    >>> dcg_at_k(r, 2)
    5.0
    >>> dcg_at_k(r, 2, method=1)
    4.2618595071429155
    >>> dcg_at_k(r, 10)
    9.6051177391888114
    >>> dcg_at_k(r, 11)
    9.6051177391888114
    Args:
        r: Relevance scores (list or numpy) in rank order
            (first element is the first item)
        k: Number of results to consider
        method: If 0 then weights are [1.0, 1.0, 0.6309, 0.5, 0.4307, ...]
                If 1 then weights are [1.0, 0.6309, 0.5, 0.4307, ...]
    Returns:
        Discounted cumulative gain
    """
    r = np.asfarray(r)[:k]
    if r.size:
        if method == 0:
            return r[0] + np.sum(r[1:] / np.log2(np.arange(2, r.size + 1)))
        elif method == 1:
            return np.sum(r / np.log2(np.arange(2, r.size + 2)))
        else:
            raise ValueError('method must be 0 or 1.')
    return 0.


def ndcg_at_k(r, k, method=0):
    """Score is normalized discounted cumulative gain (ndcg)
    Relevance is positive real values.  Can use binary
    as the previous methods.
    Example from
    http://www.stanford.edu/class/cs276/handouts/EvaluationNew-handout-6-per.pdf
    >>> r = [3, 2, 3, 0, 0, 1, 2, 2, 3, 0]
    >>> ndcg_at_k(r, 1)
    1.0
    >>> r = [2, 1, 2, 0]
    >>> ndcg_at_k(r, 4)
    0.9203032077642922
    >>> ndcg_at_k(r, 4, method=1)
    0.96519546960144276
    >>> ndcg_at_k([0], 1)
    0.0
    >>> ndcg_at_k([1], 2)
    1.0
    Args:
        r: Relevance scores (list or numpy) in rank order
            (first element is the first item)
        k: Number of results to consider
        method: If 0 then weights are [1.0, 1.0, 0.6309, 0.5, 0.4307, ...]
                If 1 then weights are [1.0, 0.6309, 0.5, 0.4307, ...]
    Returns:
        Normalized discounted cumulative gain
    """
    dcg_max = dcg_at_k(sorted(r, reverse=True), k, method)
    if not dcg_max:
        return 0.
    return dcg_at_k(r, k, method) / dcg_max